---
- name: Make sure freeipa services can pass through firewall
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ item[0].source | default(item[0]) }} service name={{ item[1] }} accept"
    permanent: true
    immediate: true
    zone: '{{ item[0].zone | default("public") }}'
    state: '{{ item[0].state | default("enabled") }}'
  with_nested:
    - '{{ freeipa_firewall_permit }}'
    - [ http, https, ldap, ldaps, kerberos, kpasswd, dns, ntp ]
  when: firewalld_enabled
  notify: reload firewalld
  tags:
    - firewall

- name: Make sure freeipa ports can pass through firewall
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ item[0].source | default(item[0]) }} port port={{ item[1].port }} protocol={{ item[1].protocol }} accept"
    permanent: true
    immediate: true
    zone: '{{ item[0].zone | default("public") }}'
    state: '{{ item[0].state | default("enabled") }}'
  with_nested:
    - '{{ freeipa_firewall_permit }}'
    - [ { port: 8443, protocol: tcp } ]
  when: firewalld_enabled
  notify: reload firewalld
  tags:
    - firewall

- name: Reload firewall
  meta: flush_handlers
