---
- name: Hard set the hostname
  hostname: name={{ ansible_fqdn }}

- name: Add host entry
  lineinfile:
    dest=/etc/hosts
    regexp=" {{ ansible_hostname }} "
    line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}"
    owner=root
    group=root
    mode=0644

- name: Run the installer
  action: command
    {{ ipaserver_base_command if inventory_hostname == ipaserver_master else ipaserver_replica_command }}
    --realm {{ ipaserver_realm }}
    --domain {{ ipaserver_domain }}
    --admin-password {{ ipaserver_admin_password }}
    -p {{ ipaserver_dir_admin_password }}
    --hostname={{ ansible_fqdn }}
    --ip-address={{ ansible_eth0.ipv4.address }}
    {{ '--idstart=%s' % ipaserver_idstart if ipaserver_idstart and inventory_hostname == ipaserver_master | default(False) else '' }}
    {{ '--idmax=%s' % ipaserver_idmax if ipaserver_idmax and inventory_hostname == ipaserver_master | default(False) else '' }}
    {{ '--forwarder=%s' % ipaserver_dns_forwarder
      if ipaserver_dns_forwarder | default(False) else '--no-forwarders' }}
    {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
    {{ '--setup-dns' if ipaserver_setup_dns | default(True) else '' }}
    {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }}
    {{ '--setup-ca' if inventory_hostname != ipaserver_master | default(False) else '' }}
    {{ '--setup-kra' if ipaserver_setup_kra | default(True) else '' }}
    {{ '--auto-reverse' if ipaserver_auto_reverse | default(True) else '' }}
    {{ '--setup-adtrust' if ipaserver_setup_adtrust | default(False) else '' }}
    {{ '--add-agents' if ipaserver_add_agents and inventory_hostname != ipaserver_master | default(False) else '' }}
    {{ '--enable-compat' if ipaserver_enable_compat | default(False) else '' }}
    {{ '--netbios-name=%s' % ipaserver_netbios_name if ipaserver_netbios_name | default(False) else '' }}
    {{ '--allow-zone-overlap' if ipaserver_allow_zone_overlap | default(False) else '' }}
    {{ '' if ipaserver_hbac_allow | default(True) else '--no_hbac_allow' }}
    {{ '' if ipaserver_setup_ntp | default(True) else '--no-ntp' }}
    {{ '' if ipaserver_configure_ssh | default(True) else '--no-ssh' }}
    {{ '' if ipaserver_configure_sshd | default(True) else '--no-sshd' }}
    {{ '' if ipaserver_ui_redirect | default(True) else '--no-ui-redirect' }}
    creates='/var/log/ipaserver-install.log'

