---

- name: Create users
  ipa_user:
    name: '{{ item.name }}'
    state: present
    givenname: '{{ item.givenname }}'
    sn: Acme
    mail: '{{ item.mail }'
    telephonenumber: '{{ item.tel }}'
    sshpubkeyfp: '{{ item.sshkeys }}'
    ipa_host: '{{ ipa_host }'
    ipa_user: admin
    ipa_pass: '{{ ipaserver_admin_password }}'
  with_items:
    - '{{ ipa_users }}'
  run_once: True

